### ISSUE TITLE
extract images from pdf occurred error

### ISSUE THREAD

**Issue by yulianzhilan** [OakwoodAI/Automagica#100]
![image-20200131135357944](https://user-images.githubusercontent.com/22515351/73515712-3dd9ed80-4431-11ea-89d2-00eb95ee7857.png)
<img width="420" alt="20200131135538" src="https://user-images.githubusercontent.com/22515351/73515778-6cf05f00-4431-11ea-9a87-a3de521c111f.png">

**Comment by koenvaneijk** [comment]
@yulianzhilan thank you for identifying this typo. We changed this in commit 561e3a9. We'll do a new release on PyPI and the Portal's bot-installer soon.
