### ISSUE TITLE
UiPath execution problem

### ISSUE THREAD

**Issue by michcikk** [OakwoodAI/Automagica#101]
Hi,

I found and resolved the issue - just letting you know.

In C:\Users\<username>\AppData\Local\Automagica\pkgs\automagica there is "activities.py"
It has four commands written like this "cmd =+ ..." and it needs to be changed to "cmd += ..." otherwise UiPath activity doesn't work.

Please fix this in future installation files :)

**Comment by tvturnhout** [comment]
Hi Michcikk,

Great find! Thank you noting this and making an issue! We will fix this ASAP.
If you would like to become an official contributor, feel free to make a pull request (and sign the CLA) :)!

**Comment by tvturnhout** [comment]
Should be fixed in the new 2.0.17 release on pypi
