### ISSUE TITLE
ExcelFile has no attribute 'to_dataframe'

### ISSUE THREAD

**Issue by michcikk** [OakwoodAI/Automagica#102]
As issue name state - 'to_dataframe' is not existent attribute to ExcelFile operations. 

![image](https://user-images.githubusercontent.com/18429179/74139006-e555dd80-4bf2-11ea-851f-f679b77d2b5d.png)

**Comment by tvturnhout** [comment]
Thanks noticing and creating an issue. This is now fixed in the new 2.0.17 release on pypi.
