### ISSUE TITLE
Error - This version of ChromeDriver only supports Chrome version 78

### ISSUE THREAD

**Issue by digobo** [OakwoodAI/Automagica#103]
Hi,

I am testing Automagica but I have a problem when I want to open a web page.

I am using Chrome version 80.0.3987.100 (official version) (64 bits) in Windows 10

I have to download the version that indicates or is there any modification I can do to make it work with the Chrome version indicated.

from automagica import *
browser = Chrome()

---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-7-e8c941af0921> in <module>
      1 # Open an automated browser
----> 2 browser = Chrome()

~\AppData\Local\Automagica\Python\lib\site-packages\automagica\utilities.py in wrapper(*args, **kwargs)
     15         logging.info("Automagica (activity): {}".format(name))
     16         telemetry(func)
---> 17         return func(*args, **kwargs)
     18 
     19     return wrapper

~\AppData\Local\Automagica\Python\lib\site-packages\automagica\activities.py in __init__(self, load_images, headless, incognito, disable_extension)
   1090 
   1091         selenium.webdriver.Chrome.__init__(self, os.path.abspath(
-> 1092             __file__).replace('activities.py', '') + chromedriver_path, chrome_options=chrome_options)
   1093 
   1094     @activity

~\AppData\Local\Automagica\pkgs\selenium\webdriver\chrome\webdriver.py in __init__(self, executable_path, port, chrome_options, service_args, desired_capabilities, service_log_path)
     67                 command_executor=ChromeRemoteConnection(
     68                     remote_server_addr=self.service.service_url),
---> 69                 desired_capabilities=desired_capabilities)
     70         except Exception:
     71             self.quit()

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webdriver.py in __init__(self, command_executor, desired_capabilities, browser_profile, proxy, keep_alive, file_detector)
    149             warnings.warn("Please use FirefoxOptions to set browser profile",
    150                           DeprecationWarning)
--> 151         self.start_session(desired_capabilities, browser_profile)
    152         self._switch_to = SwitchTo(self)
    153         self._mobile = Mobile(self)

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webdriver.py in start_session(self, capabilities, browser_profile)
    238         parameters = {"capabilities": w3c_caps,
    239                       "desiredCapabilities": capabilities}
--> 240         response = self.execute(Command.NEW_SESSION, parameters)
    241         if 'sessionId' not in response:
    242             response = response['value']

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webdriver.py in execute(self, driver_command, params)
    306         response = self.command_executor.execute(driver_command, params)
    307         if response:
--> 308             self.error_handler.check_response(response)
    309             response['value'] = self._unwrap_value(
    310                 response.get('value', None))

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\errorhandler.py in check_response(self, response)
    192         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
    193             raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
--> 194         raise exception_class(message, screen, stacktrace)
    195 
    196     def _value_or_default(self, obj, key, default):

WebDriverException: Message: session not created: This version of ChromeDriver only supports Chrome version 78

**Comment by dadokkio** [comment]
I've updated automagica this morning and now is working with machine with chrome release 80.
The problem is that some of my machine are still in 79 and I'm receiving the error:


`WebDriverException: Message: session not created: This version of ChromeDriver only supports Chrome version 80`


It's this behavior correct? It supports only the specific release and not the previous ones?

**Comment by digobo** [comment]
I have downloaded the latest version found in the following link and it worked for me.

https://github.com/OakwoodAI/Automagica/tree/368eb4797c14f8b6e7faa9315875e3d8648baa29/automagica/bin

Perform a search for "chromedriver.exe" on the entire disk C: \ and replace it all I find
