### ISSUE TITLE
RPA Challenge in Automagica 

### ISSUE THREAD

**Issue by Praseena1610** [OakwoodAI/Automagica#106]
Unable to parse and find html elements in which id gets changed.
http://www.rpachallenge.com/

**Comment by koenvaneijk** [comment]
Hi @Praseena1610 

This is actually quite easy with Automagica.

I've added the solution to our repository.

You can find it here:
https://github.com/OakwoodAI/Automagica/blob/master/examples/rpa_challenge_com_solution.ipynb

Kind regards,
Koen
Automagica.com
