### ISSUE TITLE
Can I somehow select a specific element from dropdown list on the browser Chrome

### ISSUE THREAD

**Issue by digobo** [OakwoodAI/Automagica#109]
**I have the following HTML code:**

                                <select data-toggle="tooltip" data-placement="top" title="" data-placeholder="Rol" id="cmbRol" class=" form-control parsley-validated selection" data-original-title="Rol" style="display: none;"> 
                                    <option value="Agent" data-i18n="ucontact.AGENT">Agente</option>
                                    <option value="Supervisor" data-i18n="ucontact.SUPERVISOR">Supervisor</option>
                                     
                                </select>
		<div class="chosen-container chosen-container-single chosen-container-single-nosearch" title="" id="cmbRol_chosen" style="width: 87px;">
			<a class="chosen-single">
				<span>Agente</span>
				<div><b></b></div>
			</a>
		<div class="chosen-drop">
		<div class="chosen-search">
		<input class="chosen-search-input" type="text" autocomplete="off" readonly="">
		</div>
  <ul class="chosen-results">
	<li class="active-result result-selected" data-option-array-index="0">Agente</li>
	<li class="active-result result-selected" data-option-array-index="1">Supervisor</li></ul>
		</div>
		</div>
 

---------------------------------------------------------------------------------------------

**I did the following but without success**

element = browser.find_xpath('//*[@id="cmbRol"]/option[2]')
element.click()

**I throw the following error:** 

---------------------------------------------------------------------------
ElementNotInteractableException           Traceback (most recent call last)
<ipython-input-66-3805d75f98ea> in <module>
      1 element = browser.find_xpath('//*[@id="cmbRol"]/option[2]')
----> 2 element.click()

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webelement.py in click(self)
     78     def click(self):
     79         """Clicks the element."""
---> 80         self._execute(Command.CLICK_ELEMENT)
     81 
     82     def submit(self):

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webelement.py in _execute(self, command, params)
    499             params = {}
    500         params['id'] = self._id
--> 501         return self._parent.execute(command, params)
    502 
    503     def find_element(self, by=By.ID, value=None):

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\webdriver.py in execute(self, driver_command, params)
    306         response = self.command_executor.execute(driver_command, params)
    307         if response:
--> 308             self.error_handler.check_response(response)
    309             response['value'] = self._unwrap_value(
    310                 response.get('value', None))

~\AppData\Local\Automagica\pkgs\selenium\webdriver\remote\errorhandler.py in check_response(self, response)
    192         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
    193             raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
--> 194         raise exception_class(message, screen, stacktrace)
    195 
    196     def _value_or_default(self, obj, key, default):

ElementNotInteractableException: Message: element not interactable: Element is not currently visible and may not be manipulated
  (Session info: chrome=80.0.3987.100)

**Comment by tvturnhout** [comment]
Typically an error when something is blocking the element (like a cookiewall or a popup).
Might also be the wrong element Is it a public website or any way you could share the HTML? 
That way I could try to recreate the error and perhaps come up with a solution.

**Comment by digobo** [comment]
I can't send you all the html because it's private, that's why I sent the content of the "select".

Given the content, what options are there to choose an option from the "select"?

**Comment by tvturnhout** [comment]
You could try to, after clicking on the dropdown list to type the option (or the first letter). Most webforms offer the possibility to filter on keyboard keys. Does that work?

**Comment by digobo** [comment]
I was able to solve it as follows:

1 - I click on the drop-down list
2 - I click on the option I need.

Always using the full xpath.

--------------------------------------------------

#  I click on the drop-down list
elements = browser.find_xpath('/html/body/div[3]/div/div/div/form/section[1]/div[3]/div[1]/div')
elements.click()

# I click on the option I need
Sup = browser.find_xpath('/html/body/div[3]/div/div/div/form/section[1]/div[3]/div[1]/div/div/ul/li[2]')
Sup.click()
