### ISSUE TITLE
How does it work with google g suite?

### ISSUE THREAD

**Issue by Ernesto-Valdes** [OakwoodAI/automagica#18]
google sheet and docs

**Comment by koenvaneijk** [comment]
@Ernesto-Valdes you could use the [requests ](http://docs.python-requests.org/en/master/) for this. Just make a Google Sheets or Google Docs file public through link. 

Example:

```
import requests
r = requests.get('https://docs.google.com/spreadsheets/u/0/d/1iE_vs_JSmxMTNLDpx9yfxSIy685P95r6N_7evp1Zs3w/export?format=csv
csv = r.content
```
Replace `1iE_vs_JSmxMTNLDpx9yfxSIy685P95r6N_7evp1Zs3w` with your document key (find it in the URL).

You can then use the data in CSV-format and parse it with pandas/csv-reader.
