### ISSUE TITLE
Getting the following error after `pip install` 

### ISSUE THREAD

**Issue by kanxinqing** [OakwoodAI/automagica#28]
My python version is 3.6.5
 Windows(64 bit)：
      Issues: Could not find a version that satisfies the requirement beautifulsoup4==4.6.0psutil==5.4.6 (from Automagica==0.3.1)
      I already upgrade the version of beautifulsoup4 and psutil on 4.6.0 and 5.4.6  ,but  it still not fix

**Comment by koenvaneijk** [comment]
Hi @kanxinqing thank you for opening an issue. We have pushed a newer version for Python 3.7 (latest). Could you please try installing again? Let me know if you have any issues.
