### ISSUE TITLE
Any plans for a recording feature?

### ISSUE THREAD

**Issue by Ernesto-Valdes** [OakwoodAI/automagica#29]

**Comment by koenvaneijk** [comment]
Hi Ernesto,

This is something we're looking into.

What kind of functionality would you like to record?

Kind regards,
Koen

**Comment by Ernesto-Valdes** [comment]
I'm thinking all parameters that will allow to reproduce the recording successfully.

**Comment by koenvaneijk** [comment]
Thank you for your contribution, however, this is currently not the goal of this project.
