### ISSUE TITLE
Could not install in vscode

### ISSUE THREAD

**Issue by Cemoo** [OakwoodAI/automagica#30]
I got this error while instalilng the pip

Could not find a version that satisfies the requirement sty==1.0.0b2 (from Automagica==0.3.1) (from versions: )
No matching distribution found for sty==1.0.0b2 (from Automagica==0.3.1)

Can you help me?

**Comment by Cemoo** [comment]
I solved this issue but now i am getting this error while installing on my mac on vscode 

 Could not find a version that satisfies the requirement pywin32==223 (from Automagica==0.3.1) (from versions: )
No matching distribution found for pywin32==223 (from Automagica==0.3.1)

I thought that because of that i am not using windows os, i cannot install it, but in your docs you wrote a installation about tesseract for macs so i think automagica can be install on mac. 

Can you help me please?

**Comment by tvturnhout** [comment]
We have updated to a new version and tried to fix this bug. We could not recreate it however, so could you check if it works for you?

**Comment by Cemoo** [comment]
Thanks @tvturnhout  i ll check it out

**Comment by koenvaneijk** [comment]
Closing this as no reply in a month.
