### ISSUE TITLE
Can't install on Mac OS X

### ISSUE THREAD

**Issue by vladimireduardo** [OakwoodAI/automagica#31]
On Mac OS X i had this error:
`Collecting sty==1.0.0b2 (from Automagica==0.3.1)
  Could not find a version that satisfies the requirement sty==1.0.0b2 (from Automagica==0.3.1) (from versions: )
No matching distribution found for sty==1.0.0b2 (from Automagica==0.3.1)
`
Python version: 2.7.10
Pip version: 10.0.1

**Comment by yuxuanlvmuyi** [comment]
@tvturnhout 
On Mac OS X I got this error:

Could not find a version that satisfies the requirement pywin32==223 (from Automagica==0.3.2)(from versions: )
No matching distribution found for pywin32==223 (from Automagica==0.3.2)

**Comment by koenvaneijk** [comment]
@yuxuanlvmuyi this is indeed a dependency only available for windows (pywin32). We are investigating whether there is an alternative for OSX. This is on our radar.

**Comment by rhvieira** [comment]
The problem are resolved?

**Comment by albertalegria** [comment]
Same problem here (Mac OS X):
 ERROR: Could not find a version that satisfies the requirement pywin32==223 (from Automagica==0.3.4) (from versions: none)
ERROR: No matching distribution found for pywin32==223 (from Automagica==0.3.4

**Comment by lichoil** [comment]
I got the same error on mac os:
ERROR: Could not find a version that satisfies the requirement sty==1.0.0b2 (from Automagica==0.3.4) (from versions: none)
ERROR: No matching distribution found for sty==1.0.0b2 (from Automagica==0.3.4)

this problem is resolved?

python:3.7
pip:19.1.1
mac os:10.14.5
