### ISSUE TITLE
I can not install in Ubuntu

### ISSUE THREAD

**Issue by jor1196** [OakwoodAI/automagica#32]
I have several problems installing it, I do not know if it will be by anaconda or by the version of the requirements that Automagica asks for
It is a platform with potential

**Comment by tvturnhout** [comment]
Hi jor1196, could you give us some more details on your environment and the errors you are getting?

**Comment by JosEsquivel** [comment]
Same, I first ran "pip install https://github.com/OakwoodAI/automagica/tarball/master", and an error appeared saying "from Xlib.display import Display     ModuleNotFoundError: No module named 'Xlib' ", so I installed Xlib by running "pip install python3_xlib" and I retried installing it; everything was going fine until another error popped saying that pywin32 was not satisfied and, since I am trying to install it in ubuntu, I didn't try to do more. Is it then possible to install automagica on Ubuntu? Thanks in Advice!

**Comment by koenvaneijk** [comment]
@JosEsquivel this is on our radar. We are working on resolving these issues on OSes other than Windows. We might decide to only support Windows.

**Comment by batatan** [comment]
Hi, did you decided to support other OSes than Windows? I'm having the same issue

With **pip install automagica --upgrade**

`
........Downloading https://files.pythonhosted.org/packages/0e/c2/d86ee85873005fe8b2c54cffa390a4bf6fbc0ad83c1a56d81ba7aa967bc8/py-trello-0.13.0.tar.gz
Collecting pywin32==223 (from automagica)
  ERROR: Could not find a version that satisfies the requirement pywin32==223 (from automagica) (from versions: none)
ERROR: No matching distribution found for pywin32==223 (from automagica)
`

With **pip install https://github.com/OakwoodAI/automagica/tarball/master**

`........Collecting PyAutoGUI==0.9.36 (from Automagica==1.0.6)
  Using cached https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/claudio/desa/m/bots/mercadotweets/python/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5qcn14uo/PyAutoGUI/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5qcn14uo/PyAutoGUI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-5qcn14uo/PyAutoGUI/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5qcn14uo/PyAutoGUI/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-install-5qcn14uo/PyAutoGUI/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-install-5qcn14uo/PyAutoGUI/pyautogui/_pyautogui_x11.py", line 7, in <module>
        from Xlib.display import Display
    ModuleNotFoundError: No module named 'Xlib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
