### ISSUE TITLE
How to automate mainframe with automagica

### ISSUE THREAD

**Issue by NicoForce** [OakwoodAI/automagica#33]
I want to use this library for a small project I've been doing myself which consists of mainframe automation.

In the wiki of this tool, I found that it is possible to automate mainframe using automagica; however, I haven't seen an example of it.

So I open this issue with the intention of asking how.

**Comment by tvturnhout** [comment]
Hi NicoForce, could you give us some more information about what you are trying to achieve (which software, OS, etc..).

**Comment by NicoForce** [comment]
I am using the SNA Server 3270 Applet in Windows 7.

Currently I use the Terminal Emulator in order to connect to the SNA Server, and run some Excel Macros on it in order to automate.

Needless to say, I am looking for a better tool or a better way, which is how I ended up here.

**Comment by tvturnhout** [comment]
@NicoForce That is quite specific. I am afraid we do not have any out-of-the box solutions for that. However I checked internally and our team has worked with a Terminal Emulator - SNA Sever. 

If you are looking for help you can always contact them to see if they can help out (through the contact form on www.automagica.be) would be easiest.

**Comment by NicoForce** [comment]
Thanks for your help, I'll ask there then.
