### ISSUE TITLE
Dragging leaves before the end of mouse move

### ISSUE THREAD

**Issue by dedeswim** [OakwoodAI/Automagica#37]
While trying to select some elements in PowerPoint using `DragToPosition(x, y)`, the **drag doesn't arrive to the end** of the mouse move. In fact, even though the mouse starts and ends in the right position, it doesn't select the elements I would like to.

However, if I use directly PyAutoGUI's `dragTo()` and set the duration to 1s there are no flaws.

**Comment by tvturnhout** [comment]
Dedeswim, thanks for the detailed description. Could you share with us your settings (Python version + OS ).

**Comment by dedeswim** [comment]
You're welcome, thank you for the answer. I am running:
- Python 3.7.1
- Windows 10 Pro
- Automagica 0.3.1
