### ISSUE TITLE
TypeError: PressHotkey() missing 1 required positional argument: 'second_key'

### ISSUE THREAD

**Issue by weiqiLee** [OakwoodAI/Automagica#40]
PressHotkey('win','r')
Wait(seconds=1)
Type(text='notepad', interval_seconds=0)
PressHotkey('enter')--------->PressKey('enter')
Wait(seconds=2)
Type(text='Hello world!', interval_seconds=0.15)

**Comment by tvturnhout** [comment]
Hi weiqiLee, PressHotkey is ment to have a second key as input. To only press one key we build the activity 'PressKey()'. 

We will update the example and the documentation to make this more clear, thanks for your input.
