### ISSUE TITLE
Create Ubuntu/Linux Branch (Maybe related to #32)

### ISSUE THREAD

**Issue by dkatz23238** [OakwoodAI/Automagica#44]
Hey Oakwood,

I was wondering if you have already analyzed what changes/mods must be made to Automagica to create a version that could work on remote VNC servers.

I use python RPA a lot in my job a similair project called pybotlib that I mostly use the ubuntu-branch to create RPAs for different clients and deploy them to lightweight ubuntu cloud desktops.

In my expirience only very specific windows corporation software like SAP netweaver will not run on a a linux, but most types of RPA automations can be done without a problem in linux.

I am a huge fan of automagica and would like to work on making a linux friendly version that later I could use in my package pybotlib for higher level commands. https://github.com/dkatz23238/pybotlib (Work in progress).

I will be glad, if pertinent, to create a linux branch for automagica with guidance.
If there is a known list of work to do Ill be glad to start working on it, if not I can also go ahead and analyze what needs to be changed/ported.

Many thanks!

**Comment by koenvaneijk** [comment]
Hi David,

Thanks for reaching out.

We believe there is a strong match and that our goals are very closely aligned.

Pull requests and suggestions are always welcome!

We've been working on a platform for managing Ubuntu Cloud VM desktops with noVNC (so they can be accessed through the browser) on cloud infrastructure such as Digital Ocean/GCP with the same goal as you (lightweight desktop automation). We're also making efforts to do the same, but with Windows-images, as a lot of our clients are Microsoft customers. 

If you're interested, we could get in touch and discuss further. Could you perhaps send an e-mail to koen@automagica.be with your contact details? That way we don't have to share phone numbers/etc publicly.

Looking forward to talk to you further David.

Kind regards,
Koen

**Comment by dkatz23238** [comment]
Koen, 

Will go ahead and close issue and reach out via email.
Many thanks!
