### ISSUE TITLE
Unicode support in "Type"

### ISSUE THREAD

**Issue by HenrikRyborg** [OakwoodAI/Automagica#45]
I'm trying to follow the tutorial 

from automagica import *

```
PressHotkey('win','r')
Wait(seconds=1)
Type(text='notepad', interval_seconds=0)
PressKey('enter')
Wait(seconds=2)
Type(text=str('Hello æ ø å '), interval_seconds=0)
```

Unfortunately the unicode caracters are not displayed, but the spaces are included

![image](https://user-images.githubusercontent.com/35270597/55979989-bd74b100-5c93-11e9-8f89-2fc9db9af485.png)
.

**Comment by dkatz23238** [comment]
If you need to write utf-8 encoded strings to Windows Notepad you need the file to be created/saved with utf-8 encoding. We can see if this can be facilitated by activites however ideally you should create a blank text file with utf-8 encoding and then open that file and write to it. You can do this with standard python easily.

```python
def create_utf8_file(path):
    with open(path, mode="w", encoding="utf-8") as f:
        f.write("")

create_utf8_file("myfile.txt")
```

**Comment by HenrikRyborg** [comment]
I did find a workable workaround for this issue

I figured out that the issue is in pyautogui that does not support special characters

this is my solution

from automagica import *

def type_unicode(text):
    import pyautogui
    import pyperclip
    pyperclip.copy(text)
    pyautogui.hotkey("ctrl", "v")

PressHotkey('win','r')
Wait(seconds=1)
Type(text='notepad', interval_seconds=0)
PressKey('enter')
Wait(seconds=2)
type_unicode('Hello æ ø å')

**Comment by koenvaneijk** [comment]
We are aware of this issue, thank you for raising it.

As a workaround, you can use the WScript Shell API from Windows:

```python
def Type(text=''): 
    shell = win32com.client.Dispatch("WScript.Shell")
    shell.SendKeys(str(text), 0)
```

We will be implementing this solution in Automagica's Type-function soon.
