### ISSUE TITLE
Use Snips for offline NLU and Voice AI

### ISSUE THREAD

**Issue by maelp** [OakwoodAI/Automagica#54]
At https://snips.ai we are working on a 100% private-by-design and offline Voice AI platform which would be perfectly suited for what you are doing:

 - offline library for NLU that can be used independently: https://github.com/snipsco/snips-nlu
 - use the whole platform if you also want to do offline and private-by-design speech recognition

**Comment by koenvaneijk** [comment]
Hi @maelp,

Thank you so much for your contribution.

This looks like a good addition to our Understanding-module for Automagica, especially since it is offline like you mentioned.

We will certainly take a look at this.

Kind regards,
Koen

**Comment by koenvaneijk** [comment]
Unfortunately, Snips is no longer available to my understanding, therefore closing this issue.
