### ISSUE TITLE
Fix for google.nla, should fix other stuff

### ISSUE THREAD

**Issue by winterlaite** [OakwoodAI/Automagica#55]
Hi, thanks for this software. I'm about fifteen minutes into it. Installed easily on Win7 64-bit.
Installed nla, also impressive so far. Here's a fix for the error thrown by google.nla. The old and new __init__.py are in the zip (for Python37\Lib\site-packages\nla\__init__.py, wherever that might be).
[fixes.zip](https://github.com/OakwoodAI/Automagica/files/3283116/fixes.zip)

**Comment by koenvaneijk** [comment]
@winterlaite thank you for your submission!
