### ISSUE TITLE
Converting a Word document to PDF Error

### ISSUE THREAD

**Issue by mamacmm** [OakwoodAI/Automagica#57]
My system is Windows 10
Test Converting a Word document to PDF, Find Error:
`Not implemented for other platforms than Windows.`

**Comment by burque505** [comment]
Might I ask what version of Word you are running? I don't have Office365, just MS Office 2016, which has a COM interface. I don't believe Office365 does - Automagica (as far as I know) would need com.  You can test to see if your system will support it using just Python (you already have pywin32 installed if you installed Automagic). Try this code - works 100% on my system but BE SURE to change the path names and file names, or it will NOT work for sure.
``# Modified from code at https://pbpython.com/windows-com.html
# by Winter Laite
import win32com.client as win32

word = win32.gencache.EnsureDispatch('Word.Application')
word.Visible = False
document = word.Documents.Open('C:\\Users\\You\\Documents\\YourDoc.docx')
document.SaveAs('C:\\Users\\You\\Documents\\YourDoc.pdf', FileFormat=17)
word.Quit()

**Comment by mamacmm** [comment]
Thank you for your reply. My Office is MS Office 2016.
I use the following code:
```
# Modified from code at https://pbpython.com/windows-com.html
# by Winter Laite
import win32com.client as win32

word = win32.gencache.EnsureDispatch('Word.Application')
word.Visible = False
document = word.Documents.Open('C:\\Users\\You\\Documents\\YourDoc.docx')
document.SaveAs('C:\\Users\\You\\Documents\\YourDoc.pdf', FileFormat=17)
document.Close()
word.Quit()
```
Successfully converting word to PDF
It's not clear why calling ConvertWordToPDF method fails.
I'm not very familiar with Python.
`if platform.system` should it be changed to `if platform.system()`

**Comment by koenvaneijk** [comment]
@mamacmm thanks for notifying us of this. We've made the necessary changes and the function should work now! Feel free to open a new issue if you keep having problems with the function.
