### ISSUE TITLE
can't install on mac os

### ISSUE THREAD

**Issue by lichoil** [OakwoodAI/Automagica#58]
I got  error on mac os when installing automagica using script:
# pip install https://github.com/OakwoodAI/automagica/tarball/master

ERROR: Could not find a version that satisfies the requirement sty==1.0.0b2 (from Automagica==0.3.4) (from versions: none)
ERROR: No matching distribution found for sty==1.0.0b2 (from Automagica==0.3.4)

this problem is resolved?

python:3.7
pip:19.1.1
mac os:10.14.5

**Comment by lichoil** [comment]
I've found this is an old issue posed by other guy before.
https://github.com/OakwoodAI/Automagica/issues/31

This issue is flagged as closed issue, is it fixed? 
how can I resolve this problem?

Thanks a lot

**Comment by koenvaneijk** [comment]
@lichoil could you please retry installing through pip?

We've released a new version on PyPI which should be installable through pip:
```
pip install automagica --upgrade
```
This version should be now once again be compatible with MacOS (tested on 10.14).

**Comment by IvanLjubicic** [comment]
Hi @tomspur,

could you please explain briefly how did you install it?

I have the same problem.

Thanks.
