### ISSUE TITLE
Can't locate the elements in IFrame?

### ISSUE THREAD

**Issue by zhaxingaz** [OakwoodAI/Automagica#60]
I tried to identify the elements in IFrame in two ways: "browser. find_element_by_xpath" and "browser. find_element_by_id", but the result indicated that it could not be found.

I operate in Chrome Browser.

**Comment by zhaxingaz** [comment]
# browser.find_element_by_xpath('//iframe[button/@id="su"]').submit()
# browser.find_element_by_name("iframe4").find_element_by_xpath('//*[@id="test"]').click()
# browser.find_element_by_name("iframe4").find_element_by_id("test").click()
# browser.find_element_by_name("iframe4").find_element_by_name("test1").click()
browser.find_element_by_name("iframe4").find_element_by_xpath('/html/body/button').click()

**Comment by koenvaneijk** [comment]
@zhaxingaz you can find elements in iframes by first switching to the iframe element itself and then finding elements within the iframe element.

More information here:
https://stackoverflow.com/a/24286392

The example is for Python 2, however it should be easy to convert this to Python 3.

**Comment by zhaxingaz** [comment]
@koenvaneijk thank you.
