### ISSUE TITLE
Type() with Cyrillic symbols

### ISSUE THREAD

**Issue by gureev** [OakwoodAI/Automagica#61]
How can I type Cyrillic symbols?

**Comment by koenvaneijk** [comment]
We're aware of this issue. The underlying library is not really friendly with non-English characters.

We've found a solution which we've referenced in another issue (#45) with regards to this, however it's not cross platform as it's only for Windows. That's the reason we haven't replaced the original functionality yet. 

If you would have a solution for this, feel free to make a pull request!
