### ISSUE TITLE
How can automagica automate desktop UI by finding elements - Help Needed

### ISSUE THREAD

**Issue by birsingh433** [OakwoodAI/Automagica#65]
I see the automagica libraries move the mouse to an x,y position and then perform click or type. Is there a way to get the element id and then perform the operation on the object. I mean rather than using the mouse moveTo which can work differently on different displays can this solution work directly with the desktop app GUI elements/objects
Any help is greatly appreciated.
Thanks

**Comment by burque505** [comment]
If this capability is not yet incorporated directly in Automagica, you can find and interact with UI elements using [PyWinAuto](https://pywinauto.github.io/) and [Python-UiAutomation](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows). See also [Control Pattern Mapping for UiAutomation Clients (2009)](https://docs.microsoft.com/en-us/previous-versions//dd319586(v=vs.85)).

**Comment by koenvaneijk** [comment]
@burque505 thank you for your addition.

Indeed, PyWinAuto can help with the .print_control_identifiers() method.

For more information, please review https://pywinauto.readthedocs.io/en/latest/getting_started.html
