### ISSUE TITLE
pytesseract not imported

### ISSUE THREAD

**Issue by mborcari** [OakwoodAI/Automagica#66]
Hi all,

When I use the function ExtractTextFromImage, the following erro rised:
'''
File "C:\automagicaOak\automagica\activities.py", line 556, in ExtractTextFromImage
NameError: name 'pytesseract' is not defined
'''
So, I just declared the modulo, import pytesseract, in the file activities.py, and the function worked with success.

Someone else got this error?

Envs detail:
Python 3.7.2 (32bits)
pytesseract-0.2.0
tesseract 4.0

**Comment by koenvaneijk** [comment]
@mborcari Indeed, the import seems to be missing. This will be fixed in the next version.
