### ISSUE TITLE
portal.automagica.dev

### ISSUE THREAD

**Issue by Basilio40** [OakwoodAI/Automagica#68]
Por favor desenvolvedores da Automagica criei um aplicação em meu portal e estou tendo problemas com meu Security Key .
Mandei varios e-mails para support@automagica.be e retornam todos com bloqueio .

Peço a ajuda por favor 

Grato

**Comment by koenvaneijk** [comment]
@Basilio40 we recently migrated our public Automagica Portal to another domain. Please update to the latest Automagica version (1.0.9 at time of writing this) and register at https://portal.automagica.io/.

Feel free to send an e-mail to koen@oakwood.ai if you keep facing issues with connecting and we can hop on a quick Teams meeting to get things sorted out.
