### ISSUE TITLE
__init__.py for nla is still throwing errors due to PressHotKey

### ISSUE THREAD

**Issue by burque505** [OakwoodAI/Automagica#69]
I had previously opened this, but it was closed. The error, however, persists. A fix is attached.

```
                        PressKey('enter')
```
should be the code at line 40.
[__init__.zip](https://github.com/OakwoodAI/Automagica/files/3611455/__init__.zip)

**Comment by mborcari** [comment]
For NLA, I submit a pull request, https://github.com/OakwoodAI/natural-language-automagica/pull/1

**Comment by koenvaneijk** [comment]
Merged, thanks!
