### ISSUE TITLE
After upgrade to 1.0.8, Bots remain offline on Dev portal

### ISSUE THREAD

**Issue by burque505** [OakwoodAI/Automagica#70]
Issue: Bots will not connect following upgrade to 1.0.8
Expected behavior: Bots connect
Steps to reproduce issue: 

1) Logout: "automagica --logout"
2) Upgrade from 1.0.7 to 1.0.8 via "pip install automagica -G"
3) Login: "automagica --login "16286023-9838-4948-987f-7b35356041b0"
4) Sign in to "https://portal.automagica.dev/"

Following these steps, Bots never connect.
Firewall has all rules for "python.exe", "pythonw.exe" and "automagica.exe" set to Allow.
No error messages appear during login process. Cmd.exe window disappears following apparently completed login process.

**Comment by koenvaneijk** [comment]
@burque505 thank you for raising this issue.

We have recently migrated everything from the .dev domain to our new .io domain.

Please upgrade to v1.0.9 as it also fixes an issue with upgrading to websocket connections, as the long-polling fallback connection used by the robot might not be stable enough for heavy usage.

Feel free to re-open an issue if the problem persists, or send me an e-mail to koen@oakwood.ai.
