### ISSUE TITLE
Can´t install on Linux Ubuntu

### ISSUE THREAD

**Issue by Wolvec** [OakwoodAI/Automagica#71]
When I try to install in Linux fail with the message:
  ERROR: Could not find a version that satisfies the requirement pywin32==223 (from automagica) (from versions: none)
ERROR: No matching distribution found for pywin32==223 (from automagica)

and stop the installation.

Any help?

**Comment by koenvaneijk** [comment]
Thanks @tomspur 

@Wolvec we've made some changes to Automagica to improve compatibility with Linux operating systems such as Debian- (Ubuntu) and Fedora-like (RHEL/CentOS) distributions.

Please try the latest version. If you are still having problems, don't hesitate to re-open an issue.
