### ISSUE TITLE
pywin32 and opencv-python mismatch issue while installing automagica

### ISSUE THREAD

**Issue by seeyoutonight** [OakwoodAI/Automagica#79]
I tried to install automagica in Pycharm, Win10 OS.
It shown that "No matching distribution found for opencv-python==3.4.2.17 (from Automagica==1.0.10)", which i mannully installed with version 4.1.2.30, the latest version.

Does that mean i must install the 3.4.2.17 version? I tried pip install opencv-python==3.4.2.17, also said ERROR: No matching distribution found for opencv-python==3.4.2.17.

Any advice for this? Sorry i'm a newcomer for python.

**Comment by koenvaneijk** [comment]
@seeyoutonight please create an issue where you also share the version of Python you are using. This is most likely the reason why you cannot install. Please try re-installing with the recommended version of Python (3.7) or use the one-click installer as provided on our Automagica Portal (https://portal.automagica.com)
