### ISSUE TITLE
Having this error while pip install Automagica -U

### ISSUE THREAD

**Issue by andrewwoo0902** [OakwoodAI/Automagica#80]
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from automagica) (from versions: 3.4.8.29, 4.1.2.30)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from automagica)

**Comment by navneet171996** [comment]
I am also getting the same error. In addition I am also getting the following error.

ERROR: Could not find a version that satisfies the requirement pywin32==223 (from automagica) (from versions: 225, 226, 227)
ERROR: No matching distribution found for pywin32==223 (from automagica)

**Comment by koenvaneijk** [comment]
What version of Python are you using? Have you tried with the latest version?

**Comment by gopherpy** [comment]
if you are trying to install on non windows OS, install directly from tar file. It worked for me.

**Comment by koenvaneijk** [comment]
Thanks @gopherpy 

This has been also resolved with our version 2.0 release.
