### ISSUE TITLE
Desktop Automation help

### ISSUE THREAD

**Issue by sultan-sheriff** [OakwoodAI/Automagica#81]
Hi Team,
Urgently requesting your help please!!!..
We are exploring the option of leveraging Automagica for Desktop process automation.
In this particular use case, there are requirements to click on Play button, cancel button or pencil button in Paint.
Understand Automagica expects x,y co-ordinates for the click event and if the window re-sizes it would expect its respective x,y co-ordinates.
We thought it would be really challenging to manually pass all x,y co-ordinates position on a screen.
Can you please let us know if there is an option within Automagica to do image recognition (like reference based on screenshots), it could be a great value add for Desktop based automation.
Any suggestions, thoughts or workaround to this in Automagica please?

**Comment by sultan-sheriff** [comment]
@audieleon @tvturnhout @rtroncosogar @0xflotus 
hi team 
could you please help me out to sort this issue ...

**Comment by tvturnhout** [comment]
Hi @sultan-sheriff, using mouse coördinates is one way of automating with Automagica. You could however also use the technical identifiers of the buttons like this:

```python

from pywinauto.application import Application

# Launch Paint
LaunchProcess(process_executable="mspaint.exe")
Wait(3)

# Connect to paint
app = pywinauto.Application(backend='uia')
p = pywinauto.findwindows.find_element(title_re=".* - Paint")

app.connect(handle=p.handle)
dlg = app.window(title_re=".* - Paint")

# Click all the buttons you want
dlg.child_window(best_match='Edit colours', top_level_only=True).click()
dlg.child_window(best_match='Red:Edit', top_level_only=True).set_text('r') 
dlg.child_window(best_match='Green:Edit', top_level_only=True).set_text('g') 
dlg.child_window(best_match='Blue:Edit', top_level_only=True).set_text('b')
dlg.child_window(best_match='OKButton', top_level_only=True).click()
'''

We are currently working on vision activities to solve this with image recognition, which should be a lot easier and faster to set up. We are planning to release this very soon.
