### ISSUE TITLE
Bot offline issue

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [OakwoodAI/Automagica#82]
Hello there!

This night my bot went offline and now I can't connect it again. I run in PowerShell (admin) automagica --login "00.....", it waits for a while, releases console and closes PowerShell window. After all - nothing happens. Bot still offline. I tried to create a new one bot, but with it same issue.
My configuration:
Win 10, Python 3.7.4, pip 19.3.1, automagica 1.0.11

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
Well. I do nothing and after over 40 minutes I've got a notification that bot is connected

**Comment by koenvaneijk** [comment]
We just pushed a hotfix to the public Automagica Portal a minute ago. This should resolve some connection issues some of our users were facing.
