### ISSUE TITLE
Problem with robot scheduling

### ISSUE THREAD

**Issue by abarlukova** [OakwoodAI/Automagica#84]
Dear team,

I've started to learn automagica software. 
I am trying to schedule my robot from my automagica account.
I see in "triggers" that my robot starts, for example, at 3:35 pm as shown in the picture. 

![Annotation 2019-12-26 153423](https://user-images.githubusercontent.com/32097733/71479671-aa8c1780-27f5-11ea-8f28-e05f8604f706.png)

But in one minute nothing happens. It is just rescheduled to the next day the same time. 
Please, see below. 

![Annotation 2019-12-26 153423-2](https://user-images.githubusercontent.com/32097733/71479713-f8a11b00-27f5-11ea-9716-c415d9057e04.png)

As you can see, there is no pending jobs. 

Please, could someone help me with this issue?
Thank you in advance.

**Comment by koenvaneijk** [comment]
Have you tried rescheduling the script? Try scheduling it for every hour and then schedule it back for the desired time. Let us know if you are still facing issues.

**Comment by abarlukova** [comment]
Hi,

Thank you for the prompt reply! 
I've just tried to reschedule as you proposed, but the issue remains the same...

**Comment by WendelNovaes** [comment]
Has anyone found any solution? I have the same problem.

**Comment by abarlukova** [comment]
Hi all,

Thanks for the comments. 
I found out that it worked, but just with a delay of ~1min 18 seconds.
