### ISSUE TITLE
opencv-python==3.4.2.17 not available

### ISSUE THREAD

**Issue by saurabdongre** [OakwoodAI/Automagica#85]
C:\Users>pip install https://github.com/OakwoodAI/automagica/tarball/master
Collecting https://github.com/OakwoodAI/automagica/tarball/master
  Downloading https://github.com/OakwoodAI/automagica/tarball/master
     / 45.2MB 6.4MB/s
Collecting plyer==1.4.0 (from Automagica==1.0.10)
  Using cached https://files.pythonhosted.org/packages/64/02/fa5c7054a879cfda9c937fedf8abfda6706c088da2f97c16655cf3c88626/plyer-1.4.0-py3-none-any.whl
Collecting python-socketio==4.3.0 (from Automagica==1.0.10)
  Using cached https://files.pythonhosted.org/packages/1c/5a/9429c1fbc399b6079725150a36491efd6bd4691c11110f5a57e8c991de96/python_socketio-4.3.0-py2.py3-none-any.whl
Collecting PyAutoGUI==0.9.36 (from Automagica==1.0.10)
  Using cached https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz
Collecting opencv-python==3.4.2.17 (from Automagica==1.0.10)
  ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from Automagica==1.0.10) (from versions: 3.4.8.29, 4.1.2.30)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from Automagica==1.0.10)

**Comment by koenvaneijk** [comment]
Please try this with the latest version of Automagica (v2 and up). Also make sure you are using the correct Python version.
