### ISSUE TITLE
the latest version issue. automagica --login "xxxx"  

### ISSUE THREAD

**Issue by chinaguest** [OakwoodAI/Automagica#86]
hi.

I encountered the automagica arguments issue. automagica.exe unrecognized arguments: --login. when i following the instruction to run automgaica --login. python verion: 3.7.6

**Comment by hanbalish** [comment]
Hi, it seems that the automagica --login command is no more working. I am using Automagica Robot v2.0.0 . Any advice on how to login please?

**Comment by AMAN5842** [comment]
hi,
I am facing same issue.tell us how to login om host system.

**Comment by koenvaneijk** [comment]
Please upgrade Automagica with `pip install automagica -U`, or use the installer provided in our Portal (https://portal.automagica.com). We have launched a new version of the Automagica Portal, and only the latest version of the library (v2 and up) is compatible with the new Automagica Portal. Please re-open an issue in case this did not solve your problem!
