### ISSUE TITLE
double_click_on_text not defined

### ISSUE THREAD

**Issue by wardera** [OakwoodAI/Automagica#90]
Hello,

I am experimeting with Automagica via the online portal.  If I use the canned item, I get the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-fd738a96aaa1> in <module>
      4 open_file(testfile)
      5 # Find the text with OCR and double click on it
----> 6 double_click_on_text(text='OCR Example')

NameError: name 'double_click_on_text' is not defined

I checked the documentation and the command is listed.  It looks like Automagica was updated recently, so perhaps this was deprecated.   Am I using the wrong version locally?

**Comment by koenvaneijk** [comment]
Please try `double_click_on_text_ocr`.
