### ISSUE TITLE
Help using api trigger

### ISSUE THREAD

**Issue by DarinDev1000** [OakwoodAI/Automagica#96]
When I try to use the API trigger, it returns a 404.
Url is portal.automagica.com/api.
How do I send the key? 
Bearer token?

**Comment by dhcode77** [comment]
I have the same issue.  Not sure how to use the key with API call.

**Comment by koenvaneijk** [comment]
@DarinDev1000 @dhcode77 apparently there was an issue here. The API requests should be directed to the `/api/trigger`-endpoint, while the Portal told you that it should be to `/api`. 

We provided some additional guidance with a Python example within the Portal to make it easier to find out.

Features are being added so quickly that the documentation sometimes can't keep up. We are currently working on this :-).

![image](https://user-images.githubusercontent.com/33032220/73436714-553eab00-434b-11ea-9fd6-c89d2185791e.png)

**Comment by dhcode77** [comment]
Thank you for the response.  The example makes it clear how to call from
code.
What is the syntax to make this API call directly from a browser with the
key (or from something like Insomnia)?

Thank you.

**Comment by tvturnhout** [comment]
If you would want to use the Browser I would suggest using a RESTful client:

- **Google Chrome**: Install the Postman RESTful Client, or another RESTful Client of your choice, addon for Google Chrome
- **Mozilla Firefox**: Install the RESTClient, or another RESTful Client of your choice, addon for Mozilla Firefox
- **Safari:** Install the RESTClient, or another RESTful Client of your choice, addon for Safari

**Comment by dhcode77** [comment]
Thank you for the quick response.

Another question - I just tried to use an email trigger in a test script
and received the following message in return.  I used the email address
given when I created the trigger.

[image: image.png]
