### ISSUE TITLE
Jupyter opening re-choosing default

### ISSUE THREAD

**Issue by michcikk** [OakwoodAI/Automagica#97]
I chose Microsoft Edge (new chromium version) to open jupyter notebooks links and it doesn't work with this browser - there's pop-up to open application, but after clicking "Open" nothing happens. It used to work with Firefox.

Reinstalling doesn't help and now I cannot create new scripts. Is there any way to change default app for opening jupyter notebooks?

**Comment by koenvaneijk** [comment]
@michcikk the default app being used to open the Jupyter notebook is the one you selected as default on your operating system.

In this case I assume it's Windows (Edge), therefore you can change your default browser app by going to System Settings (Windows Settings) > Default Apps. Under Web Browser you can select a different browser.

See below screenshot:

![image](https://user-images.githubusercontent.com/33032220/73435305-a7320180-4348-11ea-8be8-01c2c84e9d41.png)

**Comment by michcikk** [comment]
I tried doing this, but still doesn't work, even on different PC. 

Shouldn't I change some .py file or .json file somewhere where this is set-up?
