### ISSUE TITLE
Jupyter doesn't open - cannot edit scripts

### ISSUE THREAD

**Issue by michcikk** [OakwoodAI/Automagica#99]
I have bot connected, I have assigned script to it, but I cannot edit. When I open the "edit" list and choose "Latest" there is CMD windows popping up with "Python" name, but after few seconds it disappears and nothing happens. Doesn't work with Firefox, Edge, Chrome or Brave. What can I do?

I tried reinstalling, deleting Program Files folder, rebooting, deleting Python, installing again. But that doesn't help. I'm stuck here for 2 days now. I need to test your software for commercial use, but can't and if I can't - I cannot recommend it. :(

**Comment by jjku** [comment]
I have the same issue.

**Comment by jjku** [comment]
I tried it on another computer, but it does not work either.

**Comment by koenvaneijk** [comment]
@jjku @michcikk please share more information with us. 

How did you install Automagica? 
What OS? 
Did you try re-downloading the one-click installer from the Portal?

**Comment by jjku** [comment]
Hi,
Yes. Installed the one-click installer from the Portal (twice)

Windows 10 version 1909 build 18363.592

I installed it on another computer too just to see.. Windows 10 V2004 Build 19555.1001  (I did a fresh download of the portal onto this other computer as well)

I can add the computers to the Portal as a bot.

When I try a new script, as soon as I hit edit, the CMD prompt opens up to try to open Python.
Nothing runs in it. Just a black screen, then shuts down and nothing happens. 

Let me know if there is anything else I can try. I really want to try this thing out!

**Comment by michcikk** [comment]
I installed with installer also. 

First time I installed it was working - when you first try to edit the script it asks you which browser to choose. I chose Firefox and it opened to edit. Some scripts were not working (they needed to import "tkinter" which was somehow not installed). So I reinstalled and this time I chose Edge as default Jupyter opener. This time after clicking "edit" nothing happens apart from that "Python" console window appearing for a second.

After this I tried reinstalling many time, using different computers, defualt browsers, etc. But this pop-up for choosing which browser should open Jupyter never appeared again.

**Comment by koenvaneijk** [comment]
@michcikk there was an issue with pre-packaging `tkinter` in the one-click installer on the Automagica Portal. Apparently even though `tkinter` seems to part of the standard Python library, it's not packaged with embedded Python distributions. Probably to save space (as it's close to 10MB, which is probably a big deal for embedded devices).

With the new installer which is available on the Portal, you should no longer face the issue with activities using the `tkinter` dependencies.

**Comment by jjku** [comment]
Error when installing the new setup file

![image](https://user-images.githubusercontent.com/28010155/73668400-cea00b80-4673-11ea-9551-35b4e0339348.png)

<img width="248" alt="2020-02-03" src="https://user-images.githubusercontent.com/28010155/73668463-e11a4500-4673-11ea-8d6d-6445935fd07b.png">

**Comment by koenvaneijk** [comment]
@jjku this is probably because your Automagica Bot was still running in the background. Look for python.exe processes in the Task Manager (`ctrl`+`alt`+`del`).

**Comment by jjku** [comment]
> @jjku this is probably because your Automagica Bot was still running in the background. Look for python.exe processes in the Task Manager (`ctrl`+`alt`+`del`).

That fixed the install. However, still the same problem. Just pops open the CMD prompt and then closes it. Nothing happens.

**Comment by jjku** [comment]
On further note, I tried the new install file on another computer and it did not work.

**Comment by koenvaneijk** [comment]
@jjku this seems to be a weird compatibility issue of some sort which we have not yet come across with our users. Thank you so much for being so patient. Don't worry, we'll get to the bottom of this.

What you can try is the following in a console (assuming default installation location) by launching with the `--debug` command:
```bash
"C:\Users\User\AppData\Local\Automagica\Python\python.exe" -m automagica --edit "automagica://<SCRIPT_ID_HERE>" --debug
```
Replace the <SCRIPT_ID_HERE> with your script's ID from the Portal (can be found in the URL):
![image](https://user-images.githubusercontent.com/33032220/73688835-333b8480-46cd-11ea-8ce2-5bef32d0412a.png)



So for example:
```bash
"C:\Users\User\AppData\Local\Automagica\Python\python.exe" -m automagica --edit "automagica://8c2a4468-8fcc-4435-a5ae-7fd142aac1d6" --debug
```

By launching with the `--debug` command, the window will stay visible. 

Could you share the output with us? Preferably by e-mail to support@automagica.com so no sensitive information is compromised. Please refer to issue #99 in the subject and try to send from the e-mail you registered with at our Portal. I will closely follow up with the team to find a cause and hopefully a resolution ASAP.

**Comment by jjku** [comment]
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Automagica\pkgs\notebook\__main__.py", line 5, in <module>
    app.launch_new_instance()
  File "C:\Program Files\Automagica\pkgs\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Program Files\Automagica\pkgs\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Program Files\Automagica\pkgs\decorator.py:decorator-gen-7>", line 2, in initialize
  File "C:\Program Files\Automagica\pkgs\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Program Files\Automagica\pkgs\notebook\notebookapp.py", line 1761, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<C:\Program Files\Automagica\pkgs\decorator.py:decorator-gen-6>", line 2, in initialize
  File "C:\Program Files\Automagica\pkgs\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Program Files\Automagica\pkgs\jupyter_core\application.py", line 244, in initialize
    self.migrate_config()
  File "C:\Program Files\Automagica\pkgs\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "C:\Program Files\Automagica\pkgs\jupyter_core\migrate.py", line 247, in migrate
    with open(os.path.join(env['jupyter_config'], 'migrated'), 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Automagica\\pkgs\\automagica\\lab/.jupyter\\migrated'
Automagica's Jupyter Notebook server closed.

**Comment by jjku** [comment]
I tink I know the problem.

**Comment by jjku** [comment]
Ran the CMD prompt as Admin, and all was fine. Maybe when you launch from the browser it is not launched as admin.

**Comment by koenvaneijk** [comment]
@jjku did you perhaps install for "All Users" as Administrator? 

Seems like you installed to a non-default location as well, seems like the combination of the two is causing this issue.

Somehow it looks like your user account (non-administrator) does not have access to the required Jupyter configuration files... We'll investigate this in greater detail and will further test this scenario.

**Comment by jjku** [comment]
Yes. It was installed for All Users as Administrator.

I didn't change the default locations. It was all default.

My user account on the computer is the administrator account - or else  I can't install it nor run CMD prompt as administrator.

**Comment by michcikk** [comment]
Now that I remember - when I installed only for myself it worked and when I reainstalled it I chose option for all users and it stopped working. Maybe this is the problem. Cannot check now, will try to do all of above steps later and let you know.

**Comment by jjku** [comment]
Interestingly emough... after I did CMD prompt as administrator the first time and pushed the start first time, it looks like it is working like it should.

I can do more testing later if you'd like.

**Comment by michcikk** [comment]
On my current installation, running command above works. 

After running this from CMD I can now edit by clicking "edit" in portal. In my case - problem solved.

**Comment by tvturnhout** [comment]
Are you still encountering this problem?

**Comment by michcikk** [comment]
As I said - from my side it's solved :)
